source/ESDP_Project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ticket.urls')),
    path('accounts/', include('accounts.urls')),
]


admin.site.site_header = "Service Desk"
admin.site.site_title = "Service Desk Admin Portal"
admin.site.index_title = "Welcome to Service Desk Admin Portal!"

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/ticket/urls.py
from django.urls import path, include
from ticket.views import (TicketCreateView, TicketListView,
                          TicketDetailView, TicketUpdateView,
                          TicketCancelView, TicketCloseView,
                          ChiefInfoDetailView, SparePartUserListView,
                          SparePartAssignCreateView, TicketTimeView,
                          SparePartReturnToWarehouse, SparePartInstallation)
from ticket.views.ticket_api import ServiceObjectDetailView

app_name = 'ticket'

ticket_urlpatterns = [
    path('create/', TicketCreateView.as_view(), name='ticket_create'),
    path('<int:pk>/', TicketDetailView.as_view(), name='ticket_detail'),
    path('<int:pk>/update/', TicketUpdateView.as_view(), name='ticket_update'),
    path('<int:pk>/cancel/', TicketCancelView.as_view(), name='ticket_cancel'),
    path('<int:pk>/close/', TicketCloseView.as_view(), name='ticket_close'),
    path('<int:pk>/ticket_time/', TicketTimeView.as_view(), name='ticket_time_bar'),
    path('chief_info/', ChiefInfoDetailView.as_view(), name='ticket_chief_info'),
]

spare_part_urlpatterns = [
    path('list/', SparePartUserListView.as_view(), name='spare_parts_list'),
    path('<int:pk>/assign-spare-part/', SparePartAssignCreateView.as_view(), name='spare_part_assign_create'),
    path('<int:pk>/return-spare-part/', SparePartReturnToWarehouse.as_view(), name='spare_part_return_warehouse'),
    path('<int:pk>/install-spare-part/', SparePartInstallation.as_view(), name='spare_part_install'),
]

urlpatterns = [
    path('', TicketListView.as_view(), name='ticket_list'),
    path('ticket/', include(ticket_urlpatterns)),
    path('spare-part/', include(spare_part_urlpatterns)),
    path('service_object/<int:pk>/detail/', ServiceObjectDetailView.as_view(), name='service_object_detail_view')
]

source/ticket/models/client.py
from django.db import models
from django.core.validators import RegexValidator


class Client(models.Model):
    """
    Модель для создания клиентов(компаний)
    """
    name = models.CharField(max_length=255, verbose_name='Название')
    short_name = models.CharField(max_length=50, verbose_name='Сокращенное название')
    website = models.URLField(max_length=255, blank=True, validators=[
        RegexValidator(r'[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)')],
                              verbose_name='Вебсайт')
    email = models.EmailField(verbose_name='E-mail')
    type = models.ForeignKey('ticket.CompanyType', on_delete=models.PROTECT, verbose_name='Тип компании',
                             related_name='clients')
    address = models.CharField(max_length=255, blank=True, verbose_name='Адрес')
    country = models.ForeignKey('ticket.Country', on_delete=models.PROTECT, verbose_name='Страна',
                                related_name='clients')
    region = models.ForeignKey('ticket.Region', on_delete=models.PROTECT, verbose_name='Область',
                               related_name='clients')
    city = models.ForeignKey('ticket.City', on_delete=models.PROTECT, verbose_name='Город', related_name='clients')

    def __str__(self):
        return f'{self.short_name}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        db_table = 'client'


class CompanyType(models.Model):
    """
    Модель создания типов компаний(клиентов)
    """
    name = models.CharField(max_length=100, verbose_name='Название')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Тип компании'
        verbose_name_plural = 'Типы компаний'
        db_table = 'company_type'

source/ticket/models/contract.py
from django.db import models


class Contract(models.Model):
    """
    Модель для создания договоров
    """
    doc_number = models.CharField(max_length=50, verbose_name='№ Документа')
    date = models.DateField(auto_now_add=True, verbose_name='Дата')
    type = models.ForeignKey('ticket.ContractType', on_delete=models.PROTECT, verbose_name='Тип договора',
                             related_name='contracts')
    department = models.ForeignKey('ticket.Department', on_delete=models.PROTECT, verbose_name='Департамент',
                                   related_name='contracts')
    company_client = models.ForeignKey('ticket.Client', on_delete=models.PROTECT, verbose_name='Компания-клиент',
                                       related_name='contracts')
    valid_from = models.DateField(verbose_name='Действует с')
    valid_until = models.DateField(verbose_name='Действует до')
    status = models.ForeignKey('ticket.ContractStatus', on_delete=models.PROTECT, verbose_name='Статус',
                               related_name='contracts')

    def __str__(self):
        return f'{self.doc_number}'

    class Meta:
        verbose_name = 'Договор'
        verbose_name_plural = 'Договора'
        db_table = 'contract'


class ContractFiles(models.Model):
    contract = models.ForeignKey(
        "ticket.Contract", on_delete=models.CASCADE, related_name="contract_files"
    )
    current_document = models.FileField(upload_to='contracts', verbose_name='Действующий документ')

    def __str__(self):
        return f'{self.current_document}'

    class Meta:
        verbose_name = 'Действующий документ'
        verbose_name_plural = 'Действующие документы'
        db_table = 'contract_files'


class ContractType(models.Model):
    """
    Модель для создания типов Договора
    """
    name = models.CharField(max_length=50, verbose_name='Название')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Тип договора'
        verbose_name_plural = 'Типы договоров'
        db_table = 'contract_type'


class ContractStatus(models.Model):
    """
    Модель для создания статусов Договора
    """
    name = models.CharField(max_length=50, verbose_name='Название')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Статус договора'
        verbose_name_plural = 'Статусы договоров'
        db_table = 'contract_status'

source/ticket/models/other.py
from django.db import models


class Country(models.Model):
    """
    Модель для создания стран
    """
    name = models.CharField(max_length=100, verbose_name='Название')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'
        db_table = 'country'
        unique_together = ('name',)


class Region(models.Model):
    """
    Модель для создания стран
    """
    name = models.CharField(max_length=100, verbose_name='Название')
    country = models.ForeignKey('ticket.Country', on_delete=models.CASCADE, verbose_name='Страна',
                                related_name='regions')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Область'
        verbose_name_plural = 'Области'
        db_table = 'region'


class City(models.Model):
    """
    Модель для создания городов
    """
    name = models.CharField(max_length=100, verbose_name='Название')
    country = models.ForeignKey('ticket.Country', on_delete=models.CASCADE, verbose_name='Страна',
                                related_name='cities')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'
        db_table = 'city'


class Department(models.Model):
    """
    Модель для создания департаментов
    """
    name = models.CharField(max_length=50, verbose_name='Название')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Департамент'
        verbose_name_plural = 'Департаменты'
        db_table = 'department'

source/ticket/views/spare_part.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, ListView
from ticket.filters import SparePartUserFilter
from ticket.forms import SparePartAssignForm, SparePartAssignFormSet
from ticket.models import SparePartUser, SparePart, Ticket


class SparePartAssignCreateView(LoginRequiredMixin, CreateView):
    model = SparePartUser
    template_name = 'spare_part/assign_create.html'
    form_class = SparePartAssignForm

    def get_success_url(self):
        return reverse("ticket:ticket_detail", kwargs={"pk": self.kwargs.get("pk")})

    def get_context_data(self, **kwargs):
        ticket = get_object_or_404(Ticket, pk=self.kwargs.get("pk"))
        context = super(SparePartAssignCreateView, self).get_context_data(**kwargs)
        context['formset'] = SparePartAssignFormSet(
            queryset=SparePartUser.objects.filter(ticket_id=ticket.id, engineer_id=ticket.executor))
        context['ticket'] = ticket
        return context

    def post(self, request, *args, **kwargs):
        formset = SparePartAssignFormSet(request.POST)
        if formset.is_valid():
            return self.form_valid(formset)
        else:
            return render(request, 'spare_part/assign_create.html', {'formset': formset})

    def form_valid(self, formset):
        ticket = get_object_or_404(Ticket, pk=self.kwargs.get("pk"))
        if not ticket.executor:
            messages.error(self.request, f'У этой заявки еще не назначен инженер, назначьте инженера и '
                                         f'возвращайтесь назначать запчасти')
            return redirect('ticket:ticket_detail', pk=self.kwargs.get("pk"))
        instances = formset.save(commit=False)
        for instance in instances:
            spare_part = SparePart.objects.get(id=instance.spare_part_id)
            if instance.quantity == 0:
                messages.error(self.request, f'Вы не можете назначить запчастей в количестве: 0')
                return render(self.request, 'spare_part/assign_create.html', {'formset': formset, 'ticket': ticket})
            elif spare_part.quantity > 0 and spare_part.quantity >= instance.quantity:
                for s in SparePartUser.objects.all():
                    if s.spare_part_id == instance.spare_part_id and s.ticket_id == ticket.id:
                        messages.error(self.request, f'Назначать запчасти с одинаковыми серийными номерами нельзя!')
                        return render(self.request, 'spare_part/assign_create.html',
                                      {'formset': formset, 'ticket': ticket})
                instance.assigned_by = self.request.user
                instance.ticket = ticket
                instance.engineer = ticket.executor
                spare_part.quantity -= instance.quantity
                spare_part.save()
                instance.save()
                messages.success(self.request, f'Запчасти успешно назначены!')
                return redirect('ticket:ticket_detail', pk=self.kwargs.get("pk"))
            else:
                messages.error(self.request,
                               f'Количество запчасти {spare_part.name} на складе : {spare_part.quantity},'
                               f' а вы пытаетесь назначить : {instance.quantity}')
                return render(self.request, 'spare_part/assign_create.html', {'formset': formset, 'ticket': ticket})
        messages.warning(self.request, f'Запчасти назначены не были...')
        return super().form_valid(formset)


class SparePartUserListView(LoginRequiredMixin, ListView):
    model = SparePartUser
    template_name = 'spare_part/list.html'
    context_object_name = 'spare_parts'
    paginate_by = 6
    paginate_orphans = 0

    def get_queryset(self):
        spare_parts = super().get_queryset().select_related(
            'assigned_by', 'engineer', 'ticket', 'service_object', 'spare_part').order_by('-created_at')
        query = Q(status="assigned")
        if self.request.user.has_perm('ticket.see_engineer_tickets') and \
                self.request.user.has_perm('ticket.see_engineer_spare_parts') \
                and not self.request.user.is_superuser:
            return spare_parts.filter(engineer=self.request.user).filter(query)
        return SparePartUserFilter(self.request.GET, queryset=spare_parts).qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['filter'] = SparePartUserFilter(self.request.GET, queryset=self.get_queryset())
        return context


class SparePartReturnToWarehouse(View):
    def get(self, request, *args, **kwargs):
        spare_part = SparePartUser.objects.get(pk=kwargs.get('pk'))
        spare_part_warehouse = SparePart.objects.get(pk=spare_part.spare_part.pk)
        if spare_part.quantity == 1:
            spare_part.quantity = 0
            spare_part.status = 'returned'
            spare_part.save()
            messages.success(self.request, f'Запчасть {spare_part_warehouse} успешно возвращена на склад!')
        else:
            spare_part.quantity -= 1
            spare_part.save()
            messages.success(self.request,
                             f'Запчасть {spare_part_warehouse} в количестве: *1* успешно возвращена на склад!')
        spare_part_warehouse.quantity += 1
        spare_part_warehouse.save()
        if spare_part.status == 'returned':
            messages.error(self.request, f'Невозможно вернуть на склад, так как эта запчасть уже возвращена!')
        if spare_part.status == 'set':
            messages.error(self.request, f'Невозможно вернуть на склад, так как эта запчасть уже установлена!')
        return redirect('ticket:spare_parts_list')


class SparePartInstallation(View):
    def get(self, request, *args, **kwargs):
        spare_part = SparePartUser.objects.get(pk=kwargs.get('pk'))
        ticket = Ticket.objects.get(pk=spare_part.ticket_id)
        if (spare_part.status == 'assigned' or spare_part.status == 'set') and spare_part.quantity == 1:
            spare_part.status = 'set'
            spare_part.service_object = ticket.service_object
            spare_part.quantity -= 1
            spare_part.save()
            messages.success(self.request,
                             f'Запчасть {spare_part.spare_part} успешно установлена '
                             f'на объект {spare_part.service_object}!')
        elif (spare_part.status == 'assigned' or spare_part.status == 'set') and spare_part.quantity > 1:
            spare_part.quantity -= 1
            spare_part.service_object = ticket.service_object
            spare_part.save()
            messages.success(self.request, f'Запчасть {spare_part.spare_part} в количестве *1*'
                                           f'успешно установлена на объект {spare_part.service_object}!')
        elif spare_part.status == 'set':
            messages.error(self.request, f'Невозможно установить, так как эта запчасть уже установлена!')
        elif spare_part.status == 'returned':
            messages.error(self.request, f'Невозможно установить, так как эта запчасть уже возвращена!')
        return redirect('ticket:spare_parts_list')

source/ticket/views/ticket_api.py
from datetime import datetime
from django.http import JsonResponse
from django.views import View

from ticket.models import Ticket, ServiceObject

#  filling up with new datas
class TicketTimeView(View):
    def get(self, *args, **kwargs):
        ticket = Ticket.objects.get(id=self.kwargs.get('pk'))
        if ticket.status != "Завершенный":
            expected_time_to_finish_work = ticket.expected_finish_date
            return JsonResponse(
                {"ticket_received_at": ticket.received_at,
                 "expected_time_to_finish_work": expected_time_to_finish_work,
                 "date_time_now": datetime.now(),
                 "ticket_status": str(ticket.status.name),
                 "ticket_id": ticket.id,
                 }
            )


class ServiceObjectDetailView(View):
    def get(self, *args, **kwargs):
        service_object = ServiceObject.objects.get(id=self.kwargs.get('pk'))
        time_to_finish = service_object.time_to_fix_problem

        return JsonResponse(
            {"time_to_finish": str(time_to_finish)}
        )

source/ticket/views/ticket_custom_datetime_functions.py
import datetime, businesstimedelta, pytz


def buisnesstimedelta_function(object_):
    workday = businesstimedelta.WorkDayRule(
        start_time=datetime.time(9),
        end_time=datetime.time(18),
        working_days=[0, 1, 2, 3, 4],
        tz=pytz.timezone('Asia/Bishkek'))
    businesshours = businesstimedelta.Rules([workday])
    expected_time_to_finish = object_.expected_finish_date
    time_difference = businesshours.difference(datetime.datetime.now(), expected_time_to_finish)
    return time_difference

source/ticket/templates/spare_part/assign_create.html
{% extends 'base.html' %}
{% block title %}Назначение запчастей{% endblock %}
{% block nav %} {% endblock %}
{% block content %}
    <div class="py-2" id="icon-grid">
        <div class="alert alert-light fs-4 mb-0 text-dark" role="alert">
            Заявка-{{ ticket.received_at|date:"Ymd-His" }}
            <p class="text-muted" style="font-size: 12px">создана: {{ ticket.created_at }} &
                автор: {{ ticket.operator.get_full_name }} #
                инженер: {{ ticket.executor.get_full_name|default:'не назначен' }}</p>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 py-2">

        </div>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            {{ formset.management_form }}
            {% for form in formset %}
                {% if form.errors %}
                    <div class="spare col-md-6" style="border: 2px solid red">
                        <p><label class="text-danger" for="{{ form.id_for_label }}">{{ form.label }} {{ form }}</label>
                        </p>
                    </div>
                {% else %}
                    <div class="spare col-md-6">
                        <p><label class="form-control" for="{{ form.id_for_label }}">{{ form.label }} {{ form }}</label>
                        </p>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <input type="submit" class="btn btn-info mt-3" value="Назначить">

    </form>
    <style>
        ul.errorlist {
            margin: 0;
            padding: 0;
        }

        .errorlist li {
            border: 1px solid red;
            color: red;
            background: rgba(255, 0, 0, 0.15);
            list-style-position: inside;
            display: block;
            font-size: 1.2em;
            margin: 0 0 3px;
            padding: 4px 5px;
            text-align: center;
            border-radius: 3px;
        }
    </style>
{% endblock %}

source/ticket/templates/spare_part/list.html
{% extends 'base.html' %}
{% block title %}Запчасти{% endblock %}
{% block content %}
    <br>
    <style>
    @media screen and (max-width:456px) {
  .btn-group {
    display: flex;
    flex-direction: column;
  }
}
    </style>
    {% if object_list %}
        <form class="form-control" method="get">
            {{ filter.form }}
            &nbsp;
            <button style="margin-bottom: 2px" class="btn btn-outline-success btn-sm" type="submit">Фильтровать</button>
        </form>
        <div class="">
        <table class="table table-hover table-bordered">
            <thead>
            <tr>
                <th scope="col">Запчасть</th>
                <th class="d-none d-xl-table-cell" scope="col">Дата назначения</th>
                <th class="d-none d-lg-table-cell" scope="col">Назначена кем</th>
                <th class="d-none d-md-table-cell" scope="col">Назначена кому</th>
                <th class="d-none d-lg-table-cell" scope="col">Заявка</th>
                <th scope="col">Кол-во</th>
                <th class="d-none d-sm-table-cell" scope="col">Статус</th>
                <th scope="col">Действие</th>
            </tr>
            </thead>
            <tbody>
            {% for spare_part in spare_parts|dictsort:"id" reversed %}
                <tr>
                    <td>{{ spare_part.spare_part }}</td>
                    <td class="d-none d-xl-table-cell">{{ spare_part.created_at }}</td>
                    <td class="d-none d-lg-table-cell">{{ spare_part.assigned_by.last_name }} {{ spare_part.assigned_by.first_name }}</td>
                    <td class="d-none d-md-table-cell">{{ spare_part.engineer.last_name }} {{ spare_part.engineer.first_name }}</td>
                    {% if spare_part.ticket.pk %}
                        <td class="d-none d-lg-table-cell"><a href="{% url 'ticket:ticket_detail' spare_part.ticket.pk %}">{{ spare_part.ticket }}</a>
                        </td>
                    {% else %}
                        <td>Нет заявки</td>
                    {% endif %}
                    <td>{{ spare_part.quantity }}</td>
                    <td class="d-none d-sm-table-cell">{{ spare_part.get_status_display }}</td>
                    <td>
                        <div class="btn-group btn-group-sm" role="group" aria-label="Basic mixed styles example">
                            <a href="{% url "ticket:spare_part_install" spare_part.pk %}" class="btn btn-warning ">Установить</a>
                            <a href="{% url "ticket:spare_part_return_warehouse" spare_part.pk %}"
                               class="btn btn-success">Вернуть</a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
    {% else %}
        <br>
        <h4>Назначенных запчастей пока нет...</h4>
    {% endif %}
    {% if is_paginated %}
        {% include 'partial/pagination_spare_part.html' %}
    {% endif %}
{% endblock %}