source/ESDP_Project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ticket.urls')),
    path('accounts/', include('accounts.urls')),
]


admin.site.site_header = "Service Desk"
admin.site.site_title = "Service Desk Admin Portal"
admin.site.index_title = "Welcome to Service Desk Admin Portal!"

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/ticket/urls.py
from django.urls import path, include
from ticket.views import (TicketCreateView, TicketListView,
                          TicketDetailView, TicketUpdateView,
                          TicketCancelView, TicketCloseView,
                          ChiefInfoDetailView, SparePartUserListView,
                          SparePartAssignCreateView, TicketTimeView,
                          SparePartReturnToWarehouse, SparePartInstallation)
from ticket.views.ticket_api import ServiceObjectDetailView

app_name = 'ticket'

ticket_urlpatterns = [
    path('create/', TicketCreateView.as_view(), name='ticket_create'),
    path('<int:pk>/', TicketDetailView.as_view(), name='ticket_detail'),
    path('<int:pk>/update/', TicketUpdateView.as_view(), name='ticket_update'),
    path('<int:pk>/cancel/', TicketCancelView.as_view(), name='ticket_cancel'),
    path('<int:pk>/close/', TicketCloseView.as_view(), name='ticket_close'),
    path('<int:pk>/ticket_time/', TicketTimeView.as_view(), name='ticket_time_bar'),
    path('chief_info/', ChiefInfoDetailView.as_view(), name='ticket_chief_info'),
]

spare_part_urlpatterns = [
    path('list/', SparePartUserListView.as_view(), name='spare_parts_list'),
    path('<int:pk>/assign-spare-part/', SparePartAssignCreateView.as_view(), name='spare_part_assign_create'),
    path('<int:pk>/return-spare-part/', SparePartReturnToWarehouse.as_view(), name='spare_part_return_warehouse'),
    path('<int:pk>/install-spare-part/', SparePartInstallation.as_view(), name='spare_part_install'),
]

urlpatterns = [
    path('', TicketListView.as_view(), name='ticket_list'),
    path('ticket/', include(ticket_urlpatterns)),
    path('spare-part/', include(spare_part_urlpatterns)),
    path('service_object/<int:pk>/detail/', ServiceObjectDetailView.as_view(), name='service_object_detail_view')
]

source/ticket/models/client.py
from django.db import models
from django.core.validators import RegexValidator


class Client(models.Model):
    """
    Модель для создания клиентов(компаний)
    """
    name = models.CharField(max_length=255, verbose_name='Название')
    short_name = models.CharField(max_length=50, verbose_name='Сокращенное название')
    website = models.URLField(max_length=255, blank=True, validators=[
        RegexValidator(r'[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)')],
                              verbose_name='Вебсайт')
    email = models.EmailField(verbose_name='E-mail')
    type = models.ForeignKey('ticket.CompanyType', on_delete=models.PROTECT, verbose_name='Тип компании',
                             related_name='clients')
    address = models.CharField(max_length=255, blank=True, verbose_name='Адрес')
    country = models.ForeignKey('ticket.Country', on_delete=models.PROTECT, verbose_name='Страна',
                                related_name='clients')
    region = models.ForeignKey('ticket.Region', on_delete=models.PROTECT, verbose_name='Область',
                               related_name='clients')
    city = models.ForeignKey('ticket.City', on_delete=models.PROTECT, verbose_name='Город', related_name='clients')

    def __str__(self):
        return f'{self.short_name}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        db_table = 'client'


class CompanyType(models.Model):
    """
    Модель создания типов компаний(клиентов)
    """
    name = models.CharField(max_length=100, verbose_name='Название')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Тип компании'
        verbose_name_plural = 'Типы компаний'
        db_table = 'company_type'

source/ticket/models/contract.py
from django.db import models


class Contract(models.Model):
    """
    Модель для создания договоров
    """
    doc_number = models.CharField(max_length=50, verbose_name='№ Документа')
    date = models.DateField(auto_now_add=True, verbose_name='Дата')
    type = models.ForeignKey('ticket.ContractType', on_delete=models.PROTECT, verbose_name='Тип договора',
                             related_name='contracts')
    department = models.ForeignKey('ticket.Department', on_delete=models.PROTECT, verbose_name='Департамент',
                                   related_name='contracts')
    company_client = models.ForeignKey('ticket.Client', on_delete=models.PROTECT, verbose_name='Компания-клиент',
                                       related_name='contracts')
    valid_from = models.DateField(verbose_name='Действует с')
    valid_until = models.DateField(verbose_name='Действует до')
    status = models.ForeignKey('ticket.ContractStatus', on_delete=models.PROTECT, verbose_name='Статус',
                               related_name='contracts')

    def __str__(self):
        return f'{self.doc_number}'

    class Meta:
        verbose_name = 'Договор'
        verbose_name_plural = 'Договора'
        db_table = 'contract'


class ContractFiles(models.Model):
    contract = models.ForeignKey(
        "ticket.Contract", on_delete=models.CASCADE, related_name="contract_files"
    )
    current_document = models.FileField(upload_to='contracts', verbose_name='Действующий документ')

    def __str__(self):
        return f'{self.current_document}'

    class Meta:
        verbose_name = 'Действующий документ'
        verbose_name_plural = 'Действующие документы'
        db_table = 'contract_files'


class ContractType(models.Model):
    """
    Модель для создания типов Договора
    """
    name = models.CharField(max_length=50, verbose_name='Название')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Тип договора'
        verbose_name_plural = 'Типы договоров'
        db_table = 'contract_type'


class ContractStatus(models.Model):
    """
    Модель для создания статусов Договора
    """
    name = models.CharField(max_length=50, verbose_name='Название')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Статус договора'
        verbose_name_plural = 'Статусы договоров'
        db_table = 'contract_status'

source/ticket/models/other.py
from django.db import models


class Country(models.Model):
    """
    Модель для создания стран
    """
    name = models.CharField(max_length=100, verbose_name='Название')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'
        db_table = 'country'
        unique_together = ('name',)


class Region(models.Model):
    """
    Модель для создания стран
    """
    name = models.CharField(max_length=100, verbose_name='Название')
    country = models.ForeignKey('ticket.Country', on_delete=models.CASCADE, verbose_name='Страна',
                                related_name='regions')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Область'
        verbose_name_plural = 'Области'
        db_table = 'region'


class City(models.Model):
    """
    Модель для создания городов
    """
    name = models.CharField(max_length=100, verbose_name='Название')
    country = models.ForeignKey('ticket.Country', on_delete=models.CASCADE, verbose_name='Страна',
                                related_name='cities')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'
        db_table = 'city'


class Department(models.Model):
    """
    Модель для создания департаментов
    """
    name = models.CharField(max_length=50, verbose_name='Название')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Департамент'
        verbose_name_plural = 'Департаменты'
        db_table = 'department'

source/ticket/views/spare_part.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, ListView
from ticket.filters import SparePartUserFilter
from ticket.forms import SparePartAssignForm, SparePartAssignFormSet
from ticket.models import SparePartUser, SparePart, Ticket


class SparePartAssignCreateView(LoginRequiredMixin, CreateView):
    model = SparePartUser
    template_name = 'spare_part/assign_create.html'
    form_class = SparePartAssignForm

    def get_success_url(self):
        return reverse("ticket:ticket_detail", kwargs={"pk": self.kwargs.get("pk")})

    def get_context_data(self, **kwargs):
        ticket = get_object_or_404(Ticket, pk=self.kwargs.get("pk"))
        context = super(SparePartAssignCreateView, self).get_context_data(**kwargs)
        context['formset'] = SparePartAssignFormSet(
            queryset=SparePartUser.objects.filter(ticket_id=ticket.id, engineer_id=ticket.executor))
        context['ticket'] = ticket
        return context

    def post(self, request, *args, **kwargs):
        formset = SparePartAssignFormSet(request.POST)
        if formset.is_valid():
            return self.form_valid(formset)
        else:
            return render(request, 'spare_part/assign_create.html', {'formset': formset})

    def form_valid(self, formset):
        ticket = get_object_or_404(Ticket, pk=self.kwargs.get("pk"))
        if not ticket.executor:
            messages.error(self.request, f'У этой заявки еще не назначен инженер, назначьте инженера и '
                                         f'возвращайтесь назначать запчасти')
            return redirect('ticket:ticket_detail', pk=self.kwargs.get("pk"))
        instances = formset.save(commit=False)
        for instance in instances:
            spare_part = SparePart.objects.get(id=instance.spare_part_id)
            if instance.quantity == 0:
                messages.error(self.request, f'Вы не можете назначить запчастей в количестве: 0')
                return render(self.request, 'spare_part/assign_create.html', {'formset': formset, 'ticket': ticket})
            elif spare_part.quantity > 0 and spare_part.quantity >= instance.quantity:
                for s in SparePartUser.objects.all():
                    if s.spare_part_id == instance.spare_part_id and s.ticket_id == ticket.id:
                        messages.error(self.request, f'Назначать запчасти с одинаковыми серийными номерами нельзя!')
                        return render(self.request, 'spare_part/assign_create.html',
                                      {'formset': formset, 'ticket': ticket})
                instance.assigned_by = self.request.user
                instance.ticket = ticket
                instance.engineer = ticket.executor
                spare_part.quantity -= instance.quantity
                spare_part.save()
                instance.save()
                messages.success(self.request, f'Запчасти успешно назначены!')
                return redirect('ticket:ticket_detail', pk=self.kwargs.get("pk"))
            else:
                messages.error(self.request,
                               f'Количество запчасти {spare_part.name} на складе : {spare_part.quantity},'
                               f' а вы пытаетесь назначить : {instance.quantity}')
                return render(self.request, 'spare_part/assign_create.html', {'formset': formset, 'ticket': ticket})
        messages.warning(self.request, f'Запчасти назначены не были...')
        return super().form_valid(formset)


class SparePartUserListView(LoginRequiredMixin, ListView):
    model = SparePartUser
    template_name = 'spare_part/list.html'
    context_object_name = 'spare_parts'
    paginate_by = 6
    paginate_orphans = 0

    def get_queryset(self):
        spare_parts = super().get_queryset().select_related(
            'assigned_by', 'engineer', 'ticket', 'service_object', 'spare_part').order_by('-created_at')
        query = Q(status="assigned")
        if self.request.user.has_perm('ticket.see_engineer_tickets') and \
                self.request.user.has_perm('ticket.see_engineer_spare_parts') \
                and not self.request.user.is_superuser:
            return spare_parts.filter(engineer=self.request.user).filter(query)
        return SparePartUserFilter(self.request.GET, queryset=spare_parts).qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['filter'] = SparePartUserFilter(self.request.GET, queryset=self.get_queryset())
        return context


class SparePartReturnToWarehouse(View):
    def get(self, request, *args, **kwargs):
        spare_part = SparePartUser.objects.get(pk=kwargs.get('pk'))
        spare_part_warehouse = SparePart.objects.get(pk=spare_part.spare_part.pk)
        if spare_part.quantity == 1:
            spare_part.quantity = 0
            spare_part.status = 'returned'
            spare_part.save()
            messages.success(self.request, f'Запчасть {spare_part_warehouse} успешно возвращена на склад!')
        else:
            spare_part.quantity -= 1
            spare_part.save()
            messages.success(self.request,
                             f'Запчасть {spare_part_warehouse} в количестве: *1* успешно возвращена на склад!')
        spare_part_warehouse.quantity += 1
        spare_part_warehouse.save()
        if spare_part.status == 'returned':
            messages.error(self.request, f'Невозможно вернуть на склад, так как эта запчасть уже возвращена!')
        if spare_part.status == 'set':
            messages.error(self.request, f'Невозможно вернуть на склад, так как эта запчасть уже установлена!')
        return redirect('ticket:spare_parts_list')


class SparePartInstallation(View):
    def get(self, request, *args, **kwargs):
        spare_part = SparePartUser.objects.get(pk=kwargs.get('pk'))
        ticket = Ticket.objects.get(pk=spare_part.ticket_id)
        if (spare_part.status == 'assigned' or spare_part.status == 'set') and spare_part.quantity == 1:
            spare_part.status = 'set'
            spare_part.service_object = ticket.service_object
            spare_part.quantity -= 1
            spare_part.save()
            messages.success(self.request,
                             f'Запчасть {spare_part.spare_part} успешно установлена '
                             f'на объект {spare_part.service_object}!')
        elif (spare_part.status == 'assigned' or spare_part.status == 'set') and spare_part.quantity > 1:
            spare_part.quantity -= 1
            spare_part.service_object = ticket.service_object
            spare_part.save()
            messages.success(self.request, f'Запчасть {spare_part.spare_part} в количестве *1*'
                                           f'успешно установлена на объект {spare_part.service_object}!')
        elif spare_part.status == 'set':
            messages.error(self.request, f'Невозможно установить, так как эта запчасть уже установлена!')
        elif spare_part.status == 'returned':
            messages.error(self.request, f'Невозможно установить, так как эта запчасть уже возвращена!')
        return redirect('ticket:spare_parts_list')

source/ticket/views/ticket_api.py
from datetime import datetime
from django.http import JsonResponse
from django.views import View

from ticket.models import Ticket, ServiceObject

#  filling up with new datas
class TicketTimeView(View):
    def get(self, *args, **kwargs):
        ticket = Ticket.objects.get(id=self.kwargs.get('pk'))
        if ticket.status != "Завершенный":
            expected_time_to_finish_work = ticket.expected_finish_date
            return JsonResponse(
                {"ticket_received_at": ticket.received_at,
                 "expected_time_to_finish_work": expected_time_to_finish_work,
                 "date_time_now": datetime.now(),
                 "ticket_status": str(ticket.status.name),
                 "ticket_id": ticket.id,
                 }
            )


class ServiceObjectDetailView(View):
    def get(self, *args, **kwargs):
        service_object = ServiceObject.objects.get(id=self.kwargs.get('pk'))
        time_to_finish = service_object.time_to_fix_problem

        return JsonResponse(
            {"time_to_finish": str(time_to_finish)}
        )

source/ticket/views/ticket_custom_datetime_functions.py
import datetime, businesstimedelta, pytz


def buisnesstimedelta_function(object_):
    workday = businesstimedelta.WorkDayRule(
        start_time=datetime.time(9),
        end_time=datetime.time(18),
        working_days=[0, 1, 2, 3, 4],
        tz=pytz.timezone('Asia/Bishkek'))
    businesshours = businesstimedelta.Rules([workday])
    expected_time_to_finish = object_.expected_finish_date
    time_difference = businesshours.difference(datetime.datetime.now(), expected_time_to_finish)
    return time_difference

source/ticket/templates/ticket/cancel.html
{% extends 'base.html' %}
{% block title %}Отмена заявки{% endblock %}
{% block nav %} {% endblock %}
{% block content %}

    <div class="py-2" id="icon-grid">
        <div class="alert alert-light fs-4 mb-0 text-dark" role="alert">
            Заявка-{{ ticket.received_at|date:"Ymd-His" }}
            <p class="text-muted" style="font-size: 12px">создана: {{ ticket.created_at }} &
                автор: {{ ticket.operator.get_full_name }}</p>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 py-2">
            <div class="col d-flex align-items-start">
                <svg xmlns="http://www.w3.org/2000/svg" width="1.75em" height="1.75em" fill="currentColor"
                     class="bi bi-pc text-muted flex-shrink-0 me-3" viewBox="0 0 16 16">
                    <path d="M5 0a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V1a1 1 0 0 0-1-1H5Zm.5 14a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1Zm2 0a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1ZM5 1.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5ZM5.5 3h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1Z"/>
                </svg>
                <div>
                    <h5 class="fw-bold mb-0">Объект обслуживания</h5>
                    <p style="white-space: pre-line">{{ ticket.service_object }}
                        {{ ticket.service_object.client }}
                        {{ ticket.service_object.address|default:"Не указан" }}
                    </p>
                </div>
            </div>
        </div>
    </div>
    <form action="{% url "ticket:ticket_cancel" ticket.pk %}" method="post">
        {% csrf_token %}
        <div class="row justify-content-between">
            <div class="col-md-6">
                <label for="{{ form.cancel_reason.id_for_label }}">{{ form.cancel_reason.label }}</label>{{ form.cancel_reason }}
                {% for error in form.cancel_reason.errors %}
                    <p class="text-danger">{{ error }}</p>
                {% endfor %}
            </div>
        </div>

        <input type="submit" class="btn btn-danger btn-sm mt-3 mx-1" value="Отменить">
        <a href="{% url "ticket:ticket_detail" ticket.pk %}"
           class="btn btn-success btn-sm mt-3" style="float: left">Не отменять</a>
    </form>
{% endblock %}

source/ticket/templates/ticket/close.html
{% extends 'base.html' %}
{% block title %}Закрытие заявки{% endblock %}
{% block nav %} {% endblock %}
{% block content %}
    <div class="py-2" id="icon-grid">
        <div class="alert alert-light fs-4 mb-0 text-dark" role="alert">
            Заявка-{{ ticket.received_at|date:"Ymd-His" }}
            <p class="text-muted" style="font-size: 12px">создана: {{ ticket.created_at }} &
                автор: {{ ticket.operator.get_full_name }}</p>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 py-2">
            <div class="col d-flex align-items-start">
                <svg xmlns="http://www.w3.org/2000/svg" width="1.75em" height="1.75em" fill="currentColor"
                     class="bi bi-pc text-muted flex-shrink-0 me-3" viewBox="0 0 16 16">
                    <path d="M5 0a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V1a1 1 0 0 0-1-1H5Zm.5 14a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1Zm2 0a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1ZM5 1.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5ZM5.5 3h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1Z"/>
                </svg>
                <div>
                    <h5 class="fw-bold mb-0">Объект обслуживания</h5>
                    <p style="white-space: pre-line">{{ ticket.service_object }}
                        {{ ticket.service_object.client }}
                        {{ ticket.service_object.address|default:"Не указан" }}
                    </p>
                </div>
            </div>
        </div>
    </div>
    <form action="{% url "ticket:ticket_close" ticket.pk %}" method="post">
        {% csrf_token %}
        <div class="row justify-content-between">
            <div class="col-md-6">
                <label for="{{ form.close_commentary.id_for_label }}">{{ form.close_commentary.label }}</label>{{ form.close_commentary }}
                {% for error in form.close_commentary.errors %}
                    <p class="text-danger">{{ error }}</p>
                {% endfor %}
            </div>
        </div>

        <input type="submit" class="btn btn-dark btn-sm mt-3 mx-1" value="Закрыть">
        <a href="{% url "ticket:ticket_detail" ticket.pk %}"
           class="btn btn-success btn-sm mt-3" style="float: left">Не закрывать</a>
        <br><br>
        <div class="mb-3 form-check">
            <input type="hidden" value="Yes" name="send_email">
            <input type="checkbox" value="No" class="form-check-input" name="send_email">
            <label class="form-check-label" for="exampleCheck1">Не уведомлять клиента письмом</label>
        </div>
    </form>
{% endblock %}

source/ticket/templates/ticket/create.html
{% extends 'base.html' %}
{% block title %}Создание заявки{% endblock %}
{% block nav %} {% endblock %}
{% block content %}
    <h3 class="text-success">Новая заявка:</h3>
    <form action="#" method="post" class="needs-validation">
        {% include 'partial/form.html' with button_text="Создать" %}
    </form>
    <br>
{% endblock %}

{% block scripts %}
    <script>
        let serviceObjects = {{ service_objects|safe }};
        let clientEl = document.getElementById("id_client");
        let serviceEl = document.getElementById("id_service_object");
        clientEl.addEventListener("change", function (e) {
            let inner = '<option value="" selected="">---------</option>';
            for (let i = 0; i < serviceObjects.length; i++) {
                if (serviceObjects[i]["client_id"] == clientEl.value) {
                    inner += `<option value="${serviceObjects[i]["id"]}">${serviceObjects[i]["serial_number"]}</option>`;
                }
            }
            serviceEl.innerHTML = inner;
        });
    </script>
{% endblock %}

source/ticket/templates/ticket/list.html
{% extends 'base.html' %}
{% block title %}Заявки{% endblock %}
{% block content %}
    <br>

    {% if object_list %}
        <form class="form-control" method="get">
            {{ filter.form }}
            &nbsp;
            <button style="margin-bottom: 2px" class="btn btn-outline-success btn-sm" type="submit">Фильтровать</button>
        </form>
        <div class="">
        <table class="table table-hover table-bordered">
            <thead>
            <tr>
                <th scope="col">Заявка</th>
                <th class="d-none d-md-table-cell" scope="col">Дата получения</th>
                <th class="d-none d-sm-table-cell" scope="col">Клиент</th>
                <th class="d-none d-md-table-cell" scope="col">Объект</th>
                <th scope="col">Статус</th>
                <th class="d-none d-md-table-cell" scope="col">Прогресс</th>
            </tr>
            </thead>
            <tbody>
            {% for ticket in tickets|dictsort:"id" reversed %}
                <tr>
                    <td class="{% if ticket.priority.name == 'Высокий' %}
                table-danger
                {% elif ticket.priority.name == 'Critical Level' %}
                table-dark
                {% else %}
                table-warning
                {% endif %}">
                        <a href="{% url 'ticket:ticket_detail' ticket.pk %}">{{ ticket }}</a>
                    </td>
                    <td class="d-none d-md-table-cell">{{ ticket.received_at }}</td>
                    <td class="d-none d-sm-table-cell">{{ ticket.client }}</td>
                    <td class="d-none d-md-table-cell">{{ ticket.service_object }}</td>
                    <td>{% if ticket.status.name == 'Подготовленный' %}
                        <span class="badge rounded-pill bg-info text-dark">{{ ticket.status }}</span>
                    {% elif ticket.status.name == 'Назначенный' %}
                        <span class="badge rounded-pill bg-warning text-dark">{{ ticket.status }}</span>
                    {% elif ticket.status.name == 'На исполнении' %}
                        <span class="badge rounded-pill bg-primary">{{ ticket.status }}</span>
                    {% elif ticket.status.name == 'Исполненный' %}
                        <span class="badge rounded-pill bg-success">{{ ticket.status }}</span>
                    {% elif ticket.status.name == 'Неопределенный' %}
                        <span class="badge rounded-pill bg-secondary">{{ ticket.status }}</span>
                    {% elif ticket.status.name == 'Завершенный' %}
                        <span class="badge rounded-pill bg-dark">{{ ticket.status }}</span>
                    {% elif ticket.status.name == 'Отмененный' %}
                        <span class="badge rounded-pill bg-danger">{{ ticket.status }}</span>
                    {% else %}
                        {{ ticket.status }}
                    {% endif %}
                    </td>
                    <td class="d-none d-md-table-cell">
                    {% if not ticket.status.name == 'Завершенный' and ticket.expected_finish_date%}
                        <div class="progress">
                    <div class="progress-bar
                    {% if ticket.buisnesstimedelta_function >= 12 and ticket.get_percentage > 0 %}
                    bg-success
                    {% elif ticket.buisnesstimedelta_function < 12 and ticket.buisnesstimedelta_function > 6 and ticket.get_percentage > 0%}

                    {% elif ticket.buisnesstimedelta_function <= 6 and ticket.buisnesstimedelta_function > 3 and ticket.get_percentage > 0 %}
                    bg-warning
                    {% elif ticket.buisnesstimedelta_function <= 3 and ticket.get_percentage > 0 %}
                    bg-danger
                    {% else %}
                    bg-dark
                    {% endif %}" role="progressbar"
                         style="{% if ticket.get_percentage < 0 or ticket.buisnesstimedelta_function == 0 %}width:100%
                             {% else %}width:{{ ticket.get_percentage|add:0 }}%{% endif %}"
                         aria-valuenow="25" aria-valuemin="0"
                         aria-valuemax="100">
                        {% if ticket.get_percentage < 0 %}
                        -
                        {% endif %}
                        {{ ticket.buisnesstimedelta_function}} раб.час
                    </div>
                </div>
                    {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
    {% else %}
        <br>
        <h4>Заявок пока нет...</h4>
    {% endif %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/ticket/templates/ticket/update.html
{% extends 'base.html' %}
{% block title %}Редактирование заявки{% endblock %}
{% block nav %} {% endblock %}
{% block content %}
    <br>
    <h1>Редактировать заявку</h1>
    <form action="{% url "ticket:ticket_update" ticket.pk %}" method="post">
        {% include 'partial/form.html' with button_text="Сохранить" %}
        <a class="btn btn-primary mt-3" href="{% url 'ticket:ticket_detail' ticket.pk %}">Назад</a>
    </form>
    <br>
{% endblock %}

{% block scripts %}
    <script>
        let serviceObjects = {{ service_objects|safe }};
        let clientEl = document.getElementById("id_client");
        let serviceEl = document.getElementById("id_service_object");
        clientEl.addEventListener("change", function (e) {
            let inner = "";
            for (let i = 0; i < serviceObjects.length; i++) {
                if (serviceObjects[i]["client_id"] === clientEl.value) {
                    inner += `<option value="${serviceObjects[i]["id"]}">${serviceObjects[i]["serial_number"]}</option>`;
                }
            }
            serviceEl.innerHTML = inner;
        });
    </script>
{% endblock %}